src/objects/cb5__CBBudgetLine__c.object
<CustomObject>
    <fields>
        <fullName>cb5__NFL1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 1</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__NFL2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 2</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__NFL3__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 3</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__NFL4__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 4</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__NFL5__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 5</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Budget Line</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Budget Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cb5__CBNonFinancialLibrary__c.object
<CustomObject>
    <fields>
        <fullName>NFL1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL1</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Non-Financial Libraries</relationshipLabel>
        <relationshipName>CB_Non_Financial_Libraries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL2</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Non-Financial Libraries (NFL2)</relationshipLabel>
        <relationshipName>CB_Non_Financial_Libraries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL3</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Non-Financial Libraries (NFL3)</relationshipLabel>
        <relationshipName>CB_Non_Financial_Libraries2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL4</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Non-Financial Libraries (NFL4)</relationshipLabel>
        <relationshipName>CB_Non_Financial_Libraries3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL5</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Non-Financial Libraries (NFL5)</relationshipLabel>
        <relationshipName>CB_Non_Financial_Libraries4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__CBBudgetLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Budget Line</label>
        <referenceTo>cb5__CBBudgetLine__c</referenceTo>
        <relationshipLabel>CB Non-Financial Libraries</relationshipLabel>
        <relationshipName>CBNFLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cb5__LayerTitle__c</fullName>
        <formula>cb5__Layer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Layer Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cb5__Type__c</fullName>
        <defaultValue>&apos;Static&apos;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Static</fullName>
                    <default>true</default>
                    <label>Static</label>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Tax</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CB Non-Financial Library</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Non-Financial Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CBCategory__c.object
<CustomObject>
    <fields>
        <fullName>NFL1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL1</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Categories</relationshipLabel>
        <relationshipName>CB_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL2</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Categories (NFL2)</relationshipLabel>
        <relationshipName>CB_Categories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL3</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Categories (NFL3)</relationshipLabel>
        <relationshipName>CB_Categories2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL4</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Categories (NFL4)</relationshipLabel>
        <relationshipName>CB_Categories3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NFL5</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Categories (NFL5)</relationshipLabel>
        <relationshipName>CB_Categories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFLResult__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>NFL Result</label>
        <referenceTo>cb5__CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Categories (NFL Result)</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Category</label>
    <nameField>
        <label>CBCategory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBPayrollExpressService.cls
/** 
Copyright (c) 2024, AJR, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

 */
public with sharing class CBPayrollExpressService {

	public static void deleteUnusedNFLLibrariesServer() {
		Set<String> usedNFL = new Set<String>();
		for (cb5__CBBudgetLine__c bl : [SELECT cb5__NFL1__c,cb5__NFL2__c,cb5__NFL3__c,cb5__NFL4__c,cb5__NFL5__c FROM cb5__CBBudgetLine__c]) {
			usedNFL.add(bl.cb5__NFL1__c);
			usedNFL.add(bl.cb5__NFL2__c);
			usedNFL.add(bl.cb5__NFL3__c);
			usedNFL.add(bl.cb5__NFL4__c);
			usedNFL.add(bl.cb5__NFL5__c);
		}
		for (CBCategory__c cat : [SELECT NFL1__c,NFL2__c,NFL3__c,NFL4__c,NFL5__c,NFLResult__c,TaxThreshold__c FROM CBCategory__c]) {
			usedNFL.add(cat.NFL1__c);
			usedNFL.add(cat.NFL2__c);
			usedNFL.add(cat.NFL3__c);
			usedNFL.add(cat.NFL4__c);
			usedNFL.add(cat.NFL5__c);
			usedNFL.add(cat.NFLResult__c);
			usedNFL.add(cat.TaxThreshold__c);
		}
		for (cb5__CBNonFinancialLibrary__c lib : [SELECT Id FROM cb5__CBNonFinancialLibrary__c WHERE cb5__Type__c = 'Tax' OR cb5__LayerTitle__c LIKE '%Tax%']) {
			usedNFL.add(lib.Id);
		}
		delete [SELECT Id FROM cb5__CBNonFinancialLibrary__c WHERE Id NOT IN :usedNFL];
	}

}